services:
  - type: web
    name: SHANKAR-BOT-SS
    runtime: node
    repo: https://github.com/sk7295/SHANKAR-BOT-SS
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && \
      apt-get install -y python-is-python3 build-essential && \
      npm install --legacy-peer-deps
    startCommand: npm start
    version: "1"
